name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4    

      - name: Install Deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Browser Init
        run: rfbrowser init

      - name: Run E2E Tests
        run: robot -d ./logs -v BROWSER:firefox tests

      - name: Robot Reporter
        uses: joonvena/robotframework-reporter-action@v2.4
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }} 
          # Path to report
          report_path: logs

      - name: Upload Report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Test Report
          path: logs
