name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4    
        
      - name: Install Deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Browser Init
        run: rfbrowser init

      - name: Run E2E Tests
        run: robot -d ./logs -v BROWSER:firefox tests
